### ISSUE TITLE
Migrate null-ls to comfort

### ISSUE THREAD

**Issue by ViiEx** [ViiEx/nvchad-conf#1]
## Description

Null-ls has been archived but I am too attached to the plugin since it worked very well.
The time has come for an update and something with more features and better performance.

## Todo
- [x] Migrate everything from `null-ls` to `comfort`
- [x] Ensure format on save works.
- [x] Check that `comfort` can use formatters installed by `mason` 
- [x] Try it on different file types for testing

**Comment by ViiEx** [comment]
> [!NOTE] 
> Markdown formats fine

**Comment by ViiEx** [comment]
> [!WARNING]
> Javascript and typescript format but first throw issue related to the AutoCmd an
> finishes the format after a small delay

must investigate the above

**Comment by ViiEx** [comment]
Ready and tested!
